name: PR Check

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, and test
        run: |
          npm install
          npm run link:packages
          npm run build:packages
          npm run lint:packages
          npm run test:packages
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
