name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install, build, test and ci:publish
        run: |
          npm install
          npm run link:packages
          npm run build:packages
          npm run lint:packages
          npm run test:packages
          npm run ci:publish:packages
        env:
          CI: true
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
