name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup environment
        run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
          npm install
          npm run link:packages
          npm run build:packages
      - name: Pre-Publish packages
        run: |
          npm run pre:publish:packages --yes
      - name: Publish to NPM
        run: |
          echo //registry.npmjs.org/:_authToken=${NPM_TOKEN} > .npmrc
          npm run publish:packages --yes
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to GitHub Packages
        run: |
          echo //npm.pkg.github.com/:_authToken=${GITHUB_TOKEN} > .npmrc
          npm run publish:packages --yes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
