name: Publish

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Setup git user
        run: |
          git config --global user.email "actions@gihub.com"
          git config --global user.name "gh-actions"
      - name: Install dependencies and build packages
        run: |
          npm install
          npm run link:packages
          npm run build:packages
      - name: Pre-Publish packages
        run: |
          yes | npm run pre:publish:packages
      - name: Publish to NPM
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://registry.npmjs.org'
      - run: yes | npm run publish:packages:npm
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Publish to GitHub Packages
        uses: actions/setup-node@v1
        with:
          registry-url: 'https://npm.pkg.github.com'
          scope: '@episclera'
      - run: yes | npm run publish:packages:github
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
